query getHighlightProducts($first: Int = 10) {
  products(first: $first, where: { tagIn: ["highlight"], visibility: VISIBLE, status: "publish" }) {
    nodes {
      name
      slug
      type
      databaseId
      id
      averageRating
      reviewCount
      ...Terms
      ...ProductCategories
      ...SimpleProduct
      ...VariableProduct
      ...ExternalProduct
    }
  }
}
